
FROM debian:bookworm-slim AS builder


RUN apt-get update && \
    apt-get install -y \
    autoconf net-tools automake bison build-essential cmake curl flex wget iproute2 git libdumbnet-dev libhwloc-dev libhyperscan-dev libluajit-5.1-dev liblzma-dev libpcap-dev libpcre3-dev libssl-dev man-db pkg-config vim zlib1g-dev libnet1-dev libnetfilter-queue-dev libmnl-dev python3 pip iptables libnghttp2-dev libntirpc-dev nano zip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


WORKDIR /root
RUN git clone "https://github.com/snort3/libdaq.git" && \
    cd libdaq && \
    ./bootstrap && \
    ./configure && \
    make && \
    make install && \
    ldconfig


WORKDIR /home/snorty/src
RUN git clone "https://github.com/snort3/snort3.git" && \
    cd snort3 && \
    ./configure_cmake.sh --prefix=/home/snorty/snort3 && \
    cd build && \
    make -j$(nproc) install


WORKDIR /home/snorty/snort3/etc/rules
RUN curl -LO "https://snort.org/downloads/community/snort3-community-rules.tar.gz" && \
    tar xzf snort3-community-rules.tar.gz snort3-community-rules/snort3-community.rules --strip=1 && \
    rm snort3-community-rules.tar.gz


FROM kathara/quagga:latest


RUN apt-get update && \
    apt-get install -y \
    libfcgi0ldbl libcurl4-nss-dev lsof liblog4cxx-dev libevent-dev libleveldb-dev netcat-openbsd zsh && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


COPY --from=builder /usr/local /usr/local
COPY --from=builder /home/snorty/snort3 /home/snorty/snort3


RUN echo 'if [[ ! $PATH =~ /home/snorty/snort3/bin ]]; then export PATH=$PATH:/home/snorty/snort3/bin; fi' >> ~/.bashrc && \
    echo 'alias snort="snort -c /home/snorty/snort3/etc/snort/snort.lua"' >> ~/.bashrc && \
    echo 'export TERM=xterm-256color' >> ~/.bashrc


EXPOSE 22 80 443 8000


ENTRYPOINT ["/bin/bash"]

